TOP=../..
include $(TOP)/configure/CONFIG

DB += drvbkh.db
DB += readwrite.db
DB += b9000.db
DB += b9000RRegs.db
DB += b9000WRegs.db
DB += bkhADrv.db
DB += bkhAErr.db
DB += bkhAi.db
DB += bkhAi_simple.db
DB += bkhAo.db
DB += bkhAo_simple.db
DB += bkhBi.db
DB += bkhBi_simple.db
DB += bkhBo.db
DB += bkhBo_simple.db
DB += bkhTemp.db
DB += bkhTemp_simple.db
DB += bkhLi.db
DB += bkhLo.db
DB += bi_convert.template
DB += bo_convert.template
DB += ai_convert.template
DB += ai_convert_autosave.template

include $(TOP)/configure/RULES

