TOP=../..

include $(TOP)/configure/CONFIG

LIBRARY_IOC += bkhErr

DBD += drvBkhErr.dbd
INC += drvBkhErr.h

LIB_SRCS += drvBkhErr.cpp

LIB_LIBS += $(EPICS_BASE_IOC_LIBS)

include $(TOP)/configure/RULES

