TOP=../..

include $(TOP)/configure/CONFIG

LIBRARY_IOC += bkhMot

DBD += drvBkhAMot.dbd
INC += drvBkhAMot.h

LIB_SRCS += drvBkhAMot.cpp

LIB_LIBS += $(EPICS_BASE_IOC_LIBS)

include $(TOP)/configure/RULES

