TOP=../..

include $(TOP)/configure/CONFIG

LIBRARY_IOC += bkhAsyn

DBD += drvBkhAsyn.dbd
INC += drvBkhAsyn.h

LIB_SRCS += drvBkhAsyn.cpp

LIB_LIBS += $(EPICS_BASE_IOC_LIBS)

include $(TOP)/configure/RULES

